# Introduction {#intro}
The use of statistical methods to analyse data from agriculture and biology increased tremendeously over the past decades. This development was put forward by the availablity of cheap computing resources. Furthermore, a number of statistical software systems have become available to help scientists and practioners to analyse their own data. An important pre-requisite for the use of such statistical software systems is a good understanding of the methods that are offered by the systems used to produce the scientific results from the analysed data. This understanding is best obtained during education of students. Hence, as teachers it is important to hand over the most important insights into statistical data analysis to students of all levels.

This book offers a collection of topics that are identified as being important to understand the data analyses that are down nowadays in livestock research and industry. For reasons of space, some of the older methods had to be left out. The depth of the covered material had to be limited, but where necessary references to more material have been added. 

The material of this book is presented in a way that takes into account that most computations in statistical analyses are done using some statistics software system. As a consequence of that, the computational aspects of the analyses are not covered in very much detail. Besides the pure derivation of the formulas needed for the statistical methods, the ideas and the assumptions behind the methods are explained. 

Most of the descriptions of models or testing procedures use matrix-vector notation because it is less cumbersome compared to the older notation based on summations of scalar variables. Hence, a basic understanding of matrix and vector computations is very helpful. 

With the increasing importance of quantitative Methods in live sciences, there is a danger or a risk associated with this development. The recent development of statistical methods and the availability of cheap computing resources have led to fascinating new possibilities to answer very complex research questions. But all these technologies cannot replace critical thinking and interpretation of the results. It would be very dangerous to blindly accept results that come out of a machine without questioning them. Critical thinking and questioning requires a deaper understaning of the methods that were used by the machine. This book tries to help in getting the necessary knowledge to think about results and to question them in a critical manner.