--- 
title: "Applied Statistical Methods In Animal Science"
author: "Peter von Rohr"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [bibliography.bib]
link-citations: yes
description: "This is a book on applied statistical methods in animal science and it uses the bookdown package to produce the book. The output format for this book is set to bookdown::gitbook."
---

```{r setup, echo=FALSE}
# rmdhelp::show_knit_hook_call()
knitr::knit_hooks$set(hook_convert_odg = rmdhelp::hook_convert_odg)
met <- rmdhelp::MendeleyExportToolR6$new()
# met$set_local_bib_file(ps_local_bib_file = 'asm_in_as.bib')
met$set_this_rmd_file(ps_this_rmd_file = ifelse(rstudioapi::isAvailable(),
                              rstudioapi::getActiveDocumentContext()$path,
                              rprojroot::thisfile()))
```



# Disclaimer {-}

While teaching the three courses

* Livestock Breeding and Genomics
* Applied Statistical Methods in Animal Sciences and 
* Applied Genetic Evaluations

I was searching for a text that could be used as course notes. Once I realized that the distribution of knowledge from teacher to students via printed slides is suboptimale and as a consequence of that the need for a comprehensive text that can be used as course notes was real, I started out to write my own course notes. But after three revisions of these hand-tailored and own-written notes, the result is still not satisfactory. One of the main reason for this problem is that I realise that with three independet course notes for the three courses I end up repeating many topics several times. For students who are taking more than one of the three courses this can get either boring or confusing, because the same topic might be explained in different ways. 


## To The Recue  {-}
This project of coming up with one book that can serve as course notes for all three courses seams to be a solution that hopefully solves the problem encountered with the three independent course note texts.
